#!/usr/bin/env bash
set -euo pipefail

CFG_DIR="/etc/egress"
CFG_FILE="$CFG_DIR/config.env"
APP_DIR="/opt/egress-v2raya"

require_root() { [[ "${EUID:-$(id -u)}" -eq 0 ]] || { echo "Run as root"; exit 1; }; }
need_cmd() { command -v "$1" >/dev/null 2>&1 || { echo "Missing: $1"; exit 1; }; }

pick_primary_nic() {
  echo "Detected NICs:"
  ip -o link show | awk -F': ' '{print " - " $2}' | sed 's/@.*//'
  echo
  local defnic
  defnic="$(ip route show default 2>/dev/null | awk '{print $5}' | head -n1 || true)"
  read -rp "Primary NIC for GRE local interface [${defnic}]: " NIC
  NIC="${NIC:-$defnic}"
  [[ -n "$NIC" ]] || { echo "NIC is required"; exit 1; }
  ip link show "$NIC" >/dev/null 2>&1 || { echo "NIC not found: $NIC"; exit 1; }
  echo "$NIC"
}

read_ip() {
  local prompt="$1" var
  while true; do
    read -rp "$prompt: " var
    if python3 - <<PY 2>/dev/null
import ipaddress,sys
try:
  ipaddress.ip_address("$var")
  print("ok")
except: sys.exit(1)
PY
    then echo "$var"; return; fi
    echo "Invalid IP. Try again."
  done
}

read_cidr() {
  local prompt="$1" cidr
  while true; do
    read -rp "$prompt (e.g. 10.255.255.2/30): " cidr
    if python3 - <<PY 2>/dev/null
import ipaddress,sys
try:
  ipaddress.ip_interface("$cidr")
  print("ok")
except: sys.exit(1)
PY
    then echo "$cidr"; return; fi
    echo "Invalid CIDR. Try again."
  done
}

read_mss() {
  local mss
  while true; do
    read -rp "MSS Clamp (1200-1460 recommended): " mss
    if [[ "$mss" =~ ^[0-9]+$ ]] && (( mss>=500 && mss<=1460 )); then
      echo "$mss"; return
    fi
    echo "Invalid MSS. Use integer between 500 and 1460."
  done
}

read_lan_cidrs() {
  echo
  echo "Enter LAN CIDRs (multiple). Type 'done' when finished."
  echo "Examples: 192.168.0.0/16 , 10.10.10.0/24"
  local cidrs=()
  while true; do
    read -rp "LAN CIDR #$(( ${#cidrs[@]}+1 )): " in
    [[ "$in" == "done" ]] && break
    if ! python3 - <<PY 2>/dev/null
import ipaddress,sys
try:
  n = ipaddress.ip_network("$in", strict=False)
  # Only private ranges:
  if not (n.is_private): sys.exit(2)
except: sys.exit(1)
PY
    then
      echo "Invalid or non-private CIDR. Try again."
      continue
    fi

    # duplicate/overlap check
    local tmp_list
    tmp_list="$(printf "%s\n" "${cidrs[@]}" "$in")"
    if ! python3 - <<PY 2>/dev/null
import ipaddress,sys
nets=[]
for line in """$tmp_list""".strip().splitlines():
  n=ipaddress.ip_network(line.strip(), strict=False)
  nets.append(n)
for i in range(len(nets)):
  for j in range(i+1,len(nets)):
    if nets[i].overlaps(nets[j]):
      sys.exit(1)
print("ok")
PY
    then
      echo "CIDR overlaps with an existing entry. Try again."
      continue
    fi

    cidrs+=("$in")
  done

  if (( ${#cidrs[@]} == 0 )); then
    echo "At least one LAN CIDR is required."
    exit 1
  fi

  printf "%s," "${cidrs[@]}" | sed 's/,$//'
}

main() {
  require_root
  need_cmd ip
  need_cmd python3

  mkdir -p "$CFG_DIR"

  echo "=== Egress Config Wizard ==="
  local NIC GRE_REMOTE_IP GRE_LOCAL_CIDR GRE_NAME MSS LAN_CIDRS GUI_PORT

  NIC="$(pick_primary_nic)"
  GRE_REMOTE_IP="$(read_ip "GRE Remote Public IP (Edge Device public IP)")"
  GRE_LOCAL_CIDR="$(read_cidr "GRE Local Tunnel IP/CIDR (this server)")"

  read -rp "GRE interface name [gre-egress]: " GRE_NAME
  GRE_NAME="${GRE_NAME:-gre-egress}"

  LAN_CIDRS="$(read_lan_cidrs)"
  MSS="$(read_mss)"

  read -rp "v2rayA GUI port [2017]: " GUI_PORT
  GUI_PORT="${GUI_PORT:-2017}"
  [[ "$GUI_PORT" =~ ^[0-9]+$ ]] || { echo "Invalid port"; exit 1; }

  cat > "$CFG_FILE" <<EOF
# Generated by config-wizard.sh
PRIMARY_NIC="$NIC"
GRE_IF="$GRE_NAME"
GRE_REMOTE_IP="$GRE_REMOTE_IP"
GRE_LOCAL_CIDR="$GRE_LOCAL_CIDR"
LAN_CIDRS="$LAN_CIDRS"
MSS_CLAMP="$MSS"
V2RAYA_GUI_PORT="$GUI_PORT"

# Routing tables
PBR_TABLE_NAME="v2ray"
PBR_TABLE_ID="200"
EOF

  echo
  echo "✅ Config saved to: $CFG_FILE"
  echo
  echo "External Edge Device info will be shown next:"
  "$APP_DIR/scripts/show-external-device-info.sh" || true

  echo
  read -rp "Do you want to Activate now? (y/N): " yn
  if [[ "${yn,,}" == "y" ]]; then
    "$APP_DIR/scripts/activate.sh"
    "$APP_DIR/scripts/healthcheck.sh" || true
  else
    echo "You can activate later using: sudo egressctl -> Activate"
  fi
}

main "$@"